language: python
notifications:  
  email:  
    recipients:  
    - joel_tf_92@hotmail.com 
    on_success: always  
    on_failure: always
python:
  - "2.7"
script:
  - python hello.py
  - python lista.py
  - python suma.py
